#!/bin/bash

for path in "$@"
do
	pathLocal="`pwd`/$path"
	echo $pathLocal
	docker run -v $pathLocal:/clean segura/linter &
	pids[${i}]=$!
done

# wait for all pids
for pid in ${pids[*]}; do
    wait $pid
done
