#!/usr/bin/env php
<?php
$phpCsFixerRules = [
    '@PSR2' => true,
    'braces' => true,
    'class_definition' => true,
    'elseif'=> true,
    'function_declaration'=> true,
    'array_indentation'=> true,
    'blank_line_after_namespace'=> true,
    'lowercase_constants'=> true,
    'lowercase_keywords'=> true,
    'method_argument_space'=> true,
    'no_trailing_whitespace_in_comment'=> true,
    'no_closing_tag'=> true,
    'no_php4_constructor'=> true,
    'single_line_after_imports'=> true,
    'switch_case_semicolon_to_colon'=> true,
    'switch_case_space'=> true,
    'visibility_required'=> true,
    'no_unused_imports'=> true,
    'no_useless_else'=> true,
    'no_useless_return'=> true,
    'no_whitespace_before_comma_in_array'=> true,
    'ordered_imports'=> true,
    'ordered_class_elements'=> true,
    'array_syntax' => ['syntax' => 'short'],
    'phpdoc_order'=> true,
    'phpdoc_trim'=> true,
    'phpdoc_scalar'=> true,
    'phpdoc_separation'=> true,
];

$pathToPSR2 = "/clean";
$command = "/app/vendor/bin/php-cs-fixer fix --allow-risky=yes --cache-file=/tmp/php_cs_fixer.cache --rules='" . json_encode($phpCsFixerRules) . "' {$pathToPSR2}" ;
#system("ls -lah {$pathToPSR2}");
#echo "{$command}:";
system($command);